import { builder } from './builder';
import './enum';
import './models/user/index';
import './models/user/user.queries';
import './models/user/user.mutations';
import './models/list/index';
import './models/list/list.queries';
import './models/friendship/index';
import './models/friendship/friendship.queries';
import './models/friendship/friendship.mutations';
import './models/list/list.mutations';
import './models/listCategory/index';
import './models/listCategory/listCategory.queries';
import './models/listCategory/listCategory.mutations';
import './models/item/index';
import './models/item/item.queries';
import './models/item/item.mutations';
import './models/tag/index';
import './models/tag/tag.queries';
import './models/tag/tag.mutations';
import './models/tag/adminTag.queries';
import './models/tag/adminTag.mutations';
import './models/rating/index';
import './models/rating/rating.mutations';
import './models/randomizer/randomizer.queries';
import './models/randomizer/randomizer.mutations';
import './models/group/index';
import './models/group/group.queries';
import './models/group/group.mutations';
import './models/adminDashboard/index';
import './models/adminDashboard/adminDashboard.queries';
import './models/adminUser/index';
import './models/adminUser/adminUser.queries';
import './models/adminUser/adminUser.mutations';
import './models/notification/adminNotification.queries';
import './models/notification/adminNotification.mutations';
import './models/membership/index';
import './models/membership/adminMembership.queries';
import './models/membership/adminMembership.mutations';
import './models/report/index';
import './models/report/adminReport.queries';
import './models/report/adminReport.mutations';
import './models/payment/index';
import './models/payment/adminPayment.queries';

builder.queryType({});
builder.mutationType({});

export const schema = builder.toSchema();
