// Etichette italiane per l'enum CATEGORY (Prisma) — web non ha ancora un setup i18n come mobile,
// stesso approccio già usato nel resto del pannello admin (stringhe dirette in italiano).
export const CATEGORY_LABELS: Record<string, string> = {
  APPS: 'App',
  ART: 'Arte',
  BOOKS: 'Libri',
  NOVELS: 'Romanzi',
  COMICS: 'Fumetti',
  MANGA: 'Manga',
  SUBJECTS: 'Materie',
  MOVIES: 'Film',
  TV_SHOWS: 'Serie TV',
  MUSIC: 'Musica',
  OTHER_GAMES: 'Altri giochi',
  VIDEOGAMES: 'Videogiochi',
  BOARDGAMES: 'Giochi da tavolo',
  CARDGAMES: 'Giochi di carte',
  SHOPS: 'Negozi',
  RESTAURANTS: 'Ristoranti',
  ACTIVITIES: 'Attività',
  SERVICES: 'Servizi',
  FOOD: 'Cibo',
  CUISINE: 'Cucina',
  TRAVEL: 'Viaggi',
  FANFICTIONS: 'Fanfiction',
  VIDEOS: 'Video',
  PODCASTS: 'Podcast',
  MAGAZINES: 'Riviste',
  SPORTS: 'Sport',
  EVENTS: 'Eventi',
  EDUCATION: 'Istruzione',
  CINEMA: 'Cinema',
  THEATRE: 'Teatro',
  EXPERIENCES: 'Esperienze',
  BEVERAGES: 'Bevande',
  CUSTOM: 'Personalizzato',
};

export const ALL_CATEGORIES = Object.keys(CATEGORY_LABELS);
